const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), crypto = require('node:crypto')
const { CompanySecurity, totp, base32 } = require('../server/company-security.cjs')
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'qestima-company-')); let time = 1800000000000
  const security = new CompanySecurity({ dbPath: path.join(dir, 'company.db'), encryptionKey: crypto.randomBytes(32), now: () => time })
  t.after(() => { security.close(); fs.rmSync(dir, { recursive: true, force: true }) })
  return { s: security, next: () => time += 30000, time: () => time }
}
function admin(f) {
  const user = f.s.bootstrap(f.s.issueSetupToken(), { username: 'director', password: 'private-password-123' })
  const pending = f.s.login({ username: user.username, password: 'private-password-123' })
  const mfa = f.s.beginMfa(pending.token)
  const recovery = f.s.confirmMfa(pending.token, totp(mfa.secret, f.time()))
  f.next()
  const login = f.s.login({ username: user.username, password: 'private-password-123', code: totp(mfa.secret, f.time()) })
  return { ...login, secret: mfa.secret, recovery: recovery.recoveryCodes }
}
test('TOTP agrees with all RFC 6238 SHA1 test vectors', () => {
  const secret = base32(Buffer.from('12345678901234567890'))
  for (const [seconds, expected] of [[59,'94287082'],[1111111109,'07081804'],[1111111111,'14050471'],[1234567890,'89005924'],[2000000000,'69279037'],[20000000000,'65353130']]) assert.equal(totp(secret, seconds * 1000, 8), expected)
})
test('setup is transactional, one-time and manager enrollment cannot be bypassed', t => {
  const f = fixture(t), setup = f.s.issueSetupToken()
  assert.throws(() => f.s.bootstrap('wrong', {}), /SETUP_DENIED/)
  assert.throws(() => f.s.bootstrap(setup, { username: 'director', password: 'short' }), /PASSWORD/)
  f.s.bootstrap(setup, { username: 'director', password: 'private-password-123', role: 'viewer' })
  assert.throws(() => f.s.bootstrap(setup, {}), /SETUP_CLOSED/)
  const a = f.s.login({ username: 'director', password: 'private-password-123' })
  assert.equal(a.user.role, 'administrator'); assert.equal(a.enrollmentRequired, true)
  assert.throws(() => f.s.require(a.token, 'users.manage'), /MFA_ENROLLMENT_REQUIRED/)
})
test('MFA secrets encrypted, OTP replay rejected, enrollment session revoked', t => {
  const f = fixture(t), a = admin(f)
  assert.ok(!f.s.user(a.user.id).mfa.includes(a.secret))
  assert.ok(!JSON.stringify(a.user).includes(a.secret))
  assert.throws(() => f.s.login({ username: 'director', password: 'private-password-123', code: totp(a.secret, f.time()) }), /AUTHENTICATION_FAILED/)
  assert.ok(f.s.require(a.token, 'users.manage'))
})
test('estimator cannot self-promote; project grants and revocation are enforced', t => {
  const f = fixture(t), a = admin(f)
  const u = f.s.createUser(a.token, { username: 'engineer', password: 'engineer-password-123', role: 'estimator' })
  let e = f.s.login({ username: 'engineer', password: 'engineer-password-123' })
  assert.throws(() => f.s.changeUser(e.token, u.id, { role: 'administrator' }), /PERMISSION_DENIED/)
  assert.throws(() => f.s.require(e.token, 'commercial.view'), /PERMISSION_DENIED/)
  assert.throws(() => f.s.require(e.token, 'dry.edit', 'hospital'), /PROJECT_DENIED/)
  f.s.changeUser(a.token, u.id, { projects: ['hospital'] })
  assert.throws(() => f.s.session(e.token), /SESSION_EXPIRED/)
  e = f.s.login({ username: 'engineer', password: 'engineer-password-123' })
  assert.ok(f.s.require(e.token, 'dry.edit', 'hospital'))
  f.s.changeUser(a.token, u.id, { active: false })
  assert.throws(() => f.s.session(e.token), /SESSION_EXPIRED/)
})
test('last administrator cannot be disabled or demoted, even in favor of an unenrolled manager', t => {
  const f = fixture(t), a = admin(f)
  f.s.createUser(a.token, { username: 'manager2', password: 'manager-password-123', role: 'manager' })
  assert.throws(() => f.s.changeUser(a.token, a.user.id, { active: false }), /LAST_ADMINISTRATOR/)
  assert.throws(() => f.s.changeUser(a.token, a.user.id, { role: 'estimator' }), /LAST_ADMINISTRATOR/)
  assert.equal(f.s.user(a.user.id).active, 1)
})
test('temporary overrides expire and privileged operations need fresh authentication', t => {
  const f = fixture(t), a = admin(f)
  const u = f.s.createUser(a.token, { username: 'engineer', password: 'engineer-password-123', role: 'viewer' })
  f.s.changeUser(a.token, u.id, { projects: ['school'], overrides: { 'dry.edit': { allow: true, expiresAt: f.time() + 30000 } } })
  const e = f.s.login({ username: 'engineer', password: 'engineer-password-123' })
  assert.ok(f.s.require(e.token, 'dry.edit', 'school')); f.next()
  assert.throws(() => f.s.require(e.token, 'dry.edit', 'school'), /PERMISSION_DENIED/)
  for (let i = 0; i < 10; i++) f.next()
  assert.throws(() => f.s.changeUser(a.token, u.id, { active: false }), /REAUTHENTICATION_REQUIRED/)
  f.s.reauthenticate(a.token, 'private-password-123', totp(a.secret, f.time()))
  f.s.changeUser(a.token, u.id, { active: false })
})
test('recovery consumes recovery set, invalidates sessions, requires fresh MFA enrollment', t => {
  const f = fixture(t), a = admin(f)
  f.s.recover({ username: 'director', password: 'private-password-123', recoveryCode: a.recovery[0], newPassword: 'new-private-password-456' })
  assert.throws(() => f.s.session(a.token), /SESSION_EXPIRED/)
  assert.equal(f.s.login({ username: 'director', password: 'new-private-password-456' }).enrollmentRequired, true)
  assert.throws(() => f.s.recover({ username: 'director', password: 'new-private-password-456', recoveryCode: a.recovery[0], newPassword: 'another-password-456' }), /RECOVERY_DENIED/)
})
test('brute force attempts are limited and idle sessions expire', t => {
  const f = fixture(t), a = admin(f)
  for (let i = 0; i < 6; i++) assert.throws(() => f.s.login({ username: 'nobody', password: 'incorrect' }, 'bad-peer'), /AUTHENTICATION_FAILED/)
  assert.throws(() => f.s.login({ username: 'nobody', password: 'incorrect' }, 'bad-peer'), /TOO_MANY_ATTEMPTS/)
  for (let i = 0; i < 31; i++) f.next()
  assert.throws(() => f.s.session(a.token), /SESSION_EXPIRED/)
})
