const { contextBridge, ipcRenderer } = require("electron")

contextBridge.exposeInMainWorld("qestimaDesktop", {
  loadData: () => ipcRenderer.invoke("data:load"),
  saveData: (state) => ipcRenderer.invoke("data:save", state),
  exportBackup: (state) => ipcRenderer.invoke("backup:export", state),
  importBackup: () => ipcRenderer.invoke("backup:import"),
  pickAttachment: () => ipcRenderer.invoke("attachment:pick"),
  pickTenderDocuments: (mode) => ipcRenderer.invoke("tender:pick-documents", mode),
  pickCadDocument: (format) => ipcRenderer.invoke("cad:pick", format),
  openAttachment: (id) => ipcRenderer.invoke("attachment:open", id),
  extractPdfText: (attachmentId) => ipcRenderer.invoke("pdf:extract", attachmentId),
  renderPdfPage: (payload) => ipcRenderer.invoke("pdf:render-page", payload),
  readPdfBytes: (id) => ipcRenderer.invoke("pdf:read-bytes", id),
  inspectCadDocument: (attachmentId) => ipcRenderer.invoke("cad:inspect", attachmentId),
  pickIfcModel: () => ipcRenderer.invoke("model:pick-ifc"),
  extractIfcModel: (attachmentId) => ipcRenderer.invoke("model:extract-ifc", attachmentId),
  centralRequest: (payload) => ipcRenderer.invoke("central:request", payload),
  exportProjectPackage: (state, passphrase) => ipcRenderer.invoke("project:export-package", { state, passphrase }),
  importProjectPackage: (passphrase) => ipcRenderer.invoke("project:import-package", passphrase),
  exportPdf: (html, suggestedName) => ipcRenderer.invoke("report:pdf", html, suggestedName),
  exportReportPack: (payload) => ipcRenderer.invoke("report:pack", payload),
  verifyLicenseToken: (token, publicKeyPem) => ipcRenderer.invoke("license:verify-token", token, publicKeyPem),
  verifyUpdateManifest: (manifest, publicKeyPem) => ipcRenderer.invoke("updates:verify-manifest", manifest, publicKeyPem),
  platform: process.platform,
  commercialBuild: true,
})
